name: Python CI

on:
  push:
    branches-ignore: []  # This will trigger on pushes to any branch
  pull_request:
    branches-ignore: []  # This will trigger on pull requests targeting any branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Run tests
      run: pytest /test/test_app.py  # Run the tests

    - name: Run black (reformat code)
      run: black .  # Automatically reformat the code according to black's standards

    - name: Commit and push if changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Apply black formatting" -a || true  # This will not fail if there's nothing to commit
        git push
