name: Python CI

on:
  push:
    branches-ignore: []  # This will trigger on pushes to any branch
  pull_request:
    branches-ignore: []  # This will trigger on pull requests targeting any branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest or your test runner
        pip install pylint  # Install pylint for code quality checks
        pip install -r requirements.txt  # Install other project dependencies

    - name: Run tests
      run: pytest tests/test_app.py  # Run the tests

    - name: Lint with pylint
      run: |
        # Run pylint on all python files
        pylint $(find . -type f -name "*.py")
